create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    display_name varchar(80) not null,
    created_at timestamp not null default current_timestamp
);

create table exercise (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    name varchar(100) not null,
    description text,
    created_at timestamp not null default current_timestamp
);

create table training (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    training_date date not null,
    note text,
    created_at timestamp not null default current_timestamp
);

create table training_set (
    id bigint generated by default as identity primary key,
    training_id bigint not null references training(id) on delete cascade,
    exercise_id bigint not null references exercise(id),
    reps int not null check (reps > 0),
    weight numeric(7, 2) not null check (weight >= 0),
    created_at timestamp not null default current_timestamp
);

create index idx_exercise_user on exercise(user_id);
create index idx_training_user_date on training(user_id, training_date);
create index idx_training_set_exercise on training_set(exercise_id);
create index idx_training_set_training on training_set(training_id);

insert into app_user (id, username, display_name)
values (1, 'demo', 'Demo User');
